apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  # TODO - this should be changed once we deploy AAT to AKS
  REFORM_ENVIRONMENT: "aat"
  NODE_ENV: "production"
